### ISSUE TITLE
NullPointerException for domain and range

### ISSUE THREAD

**Issue by tudorache** [protegeproject/ontograf#7]
Reported on the mailing list:

Error 1 Logged at Tue Dec 23 09:10:15 CST 2014

NullPointerException: null

    java.util.TreeMap.compare(Unknown Source)

    java.util.TreeMap.put(Unknown Source)

    java.util.TreeSet.add(Unknown Source)

    org.protege.ontograf.common.ProtegeGraphModel.createDomainRangeRels(ProtegeGraphModel.java:586)

    org.protege.ontograf.common.ProtegeGraphModel.getDomainRangeRelationships(ProtegeGraphModel.java:599)

    org.protege.ontograf.common.ProtegeGraphModel.loadDomainRangeRels(ProtegeGraphModel.java:285)

    org.protege.ontograf.common.ProtegeGraphModel.createIncomingRelationships(ProtegeGraphModel.java:252)

    org.protege.ontograf.common.ProtegeGraphModel.show(ProtegeGraphModel.java:110)

    org.protege.ontograf.common.GraphController.showOWLClass(GraphController.java:225)

    org.protege.ontograf.OntoGrafView.updateView(OntoGrafView.java:219)

    org.protege.editor.owl.ui.view.cls.AbstractOWLClassViewComponent.updateView(AbstractOWLClassViewComponent.java:36)

    org.protege.editor.owl.ui.view.cls.AbstractOWLClassViewComponent.updateView(AbstractOWLClassViewComponent.java:19)

    org.protege.editor.owl.ui.view.AbstractOWLSelectionViewComponent.updateViewContentAndHeader(AbstractOWLSelectionViewComponent.java:202)

    org.protege.editor.owl.ui.view.AbstractOWLSelectionViewComponent.initialiseOWLView(AbstractOWLSelectionViewComponent.java:119)

    org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:61)

    org.protege.editor.core.ui.view.View.createContent(View.java:439)

    org.protege.editor.core.ui.view.View.createUI(View.java:219)

    org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:149)

    java.awt.Component.processHierarchyEvent(Unknown Source)

    java.awt.Component.processEvent(Unknown Source)

    java.awt.Container.processEvent(Unknown Source)

    java.awt.Component.dispatchEventImpl(Unknown Source)

    java.awt.Container.dispatchEventImpl(Unknown Source)

    java.awt.Component.dispatchEvent(Unknown Source)

    java.awt.Component.createHierarchyEvents(Unknown Source)

    java.awt.Container.createHierarchyEvents(Unknown Source)

    java.awt.Container.createHierarchyEvents(Unknown Source)

    java.awt.Container.createHierarchyEvents(Unknown Source)

    java.awt.Container.createHierarchyEvents(Unknown Source)

    java.awt.Container.createHierarchyEvents(Unknown Source)

    java.awt.Component.show(Unknown Source)

    java.awt.Component.show(Unknown Source)

    java.awt.Component.setVisible(Unknown Source)

    javax.swing.JComponent.setVisible(Unknown Source)

    javax.swing.JTabbedPane.fireStateChanged(Unknown Source)

    javax.swing.JTabbedPane$ModelListener.stateChanged(Unknown Source)

    javax.swing.DefaultSingleSelectionModel.fireStateChanged(Unknown Source)

    javax.swing.DefaultSingleSelectionModel.setSelectedIndex(Unknown Source)

    javax.swing.JTabbedPane.setSelectedIndexImpl(Unknown Source)

    javax.swing.JTabbedPane.setSelectedIndex(Unknown Source)

    javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(Unknown Source)

    java.awt.Component.processMouseEvent(Unknown Source)

    javax.swing.JComponent.processMouseEvent(Unknown Source)

    java.awt.Component.processEvent(Unknown Source)

    java.awt.Container.processEvent(Unknown Source)

    java.awt.Component.dispatchEventImpl(Unknown Source)

    java.awt.Container.dispatchEventImpl(Unknown Source)

    java.awt.Component.dispatchEvent(Unknown Source)

    java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)

    java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)

    java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)

    java.awt.Container.dispatchEventImpl(Unknown Source)

    java.awt.Window.dispatchEventImpl(Unknown Source)

    java.awt.Component.dispatchEvent(Unknown Source)

    java.awt.EventQueue.dispatchEventImpl(Unknown Source)

    java.awt.EventQueue.access$400(Unknown Source)

    java.awt.EventQueue$3.run(Unknown Source)

    java.awt.EventQueue$3.run(Unknown Source)

    java.security.AccessController.doPrivileged(Native Method)

    java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)

    java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)

    java.awt.EventQueue$4.run(Unknown Source)

    java.awt.EventQueue$4.run(Unknown Source)

    java.security.AccessController.doPrivileged(Native Method)

    java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)

    java.awt.EventQueue.dispatchEvent(Unknown Source)

    java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)

    java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)

    java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)

    java.awt.EventDispatchThread.pumpEvents(Unknown Source)

    java.awt.EventDispatchThread.pumpEvents(Unknown Source)

    java.awt.EventDispatchThread.run(Unknown Source)

---------------------------------------------------------------------------------------------------

protege-259.log

INFO  Starting Protege Desktop (Version 5.0.0, Build = beta-15)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Platform:  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO      Java: JVM 1.8.0_25-b18 Memory: 259M  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO      Language: en, Country: US  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO      Framework: Apache Software Foundation (1.5)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO      OS: windows7 (6.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO      Processor: x86  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Cajun Visualization Library (1.0.2)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Guava: Google Core Libraries for Java (17.0.0)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: DL Query (1.1.4)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: OWLViz (4.1.4)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Protege OWL Code Generation (1.1.0.2013_04_03_1042)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: OWL Difference (4.1.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Protege Editor OWL (5.0.0.beta-15)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Protege SPARQL Plugin (1.0.0)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Explanation Workbench (1.0.0)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Protege HermiT Integration (1.0.0)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: OntoGraf (1.0.3)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: OWL Difference Engine (1.0.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: OWLAPI RDF Library (1.0.2)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: OWLAPI Distribution (3.5.0)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: ACE View Tab (1.3.1.2011_03_18_1133)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Pellet Reasoner Plug-in (2.2.0)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: OWL2Query Protege Plug-in (1.0.0)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: OWLDiff Protege plugin (0.2.0)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Annotation Template View (2.1.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Bookmark View (1.2.3)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: OWLDoc (2.0.0)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Cardinality View (1.1.2)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Change (1.1.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Cloud Views (1.1.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Existential Tree (1.1.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Matrix Views (1.1.2)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: OBO tools (1.1.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Annotation Search (1.1.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: BeanShell (1.1.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: Taxonomy Example View (1.1.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: URI Utilities (1.1.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: HermiT Reasoner (1.3.8)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Plugin: SADI plugin (1.2.1)  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  	Cajun Visualization Library Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  	Guava: Google Core Libraries for Java Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  	OWL Difference Engine Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  	OWLAPI RDF Library Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  	OWLAPI Distribution Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Using OWL API version 3.5.0  org.protege.editor.owl.OWLEditorKit[FelixDispatchQueue]
INFO  Rebuilding entity indices...  org.protege.editor.owl.model.OWLModelManagerImpl[FelixDispatchQueue]
INFO  ... rebuilt in 0 ms  org.protege.editor.owl.model.OWLModelManagerImpl[FelixDispatchQueue]
INFO  Setting active ontology to OntologyID(OntologyIRI(<http://www.semanticweb.org/dr.kofinyamekye/ontologies/2014/11/untitled-ontology-268>))  org.protege.editor.owl.model.OWLModelManagerImpl[FelixDispatchQueue]
INFO  Rebuilding entity indices...  org.protege.editor.owl.model.OWLModelManagerImpl[FelixDispatchQueue]
INFO  ... rebuilt in 0 ms  org.protege.editor.owl.model.OWLModelManagerImpl[FelixDispatchQueue]
INFO  ... active ontology changed  org.protege.editor.owl.model.OWLModelManagerImpl[FelixDispatchQueue]
INFO  Cannot generate ontology catalog for ontology at http://www.semanticweb.org/dr.kofinyamekye/ontologies/2014/11/untitled-ontology-268  org.protege.editor.owl.model.OWLModelManagerImpl[FelixDispatchQueue]
INFO  Setting active ontology to OntologyID(OntologyIRI(<http://www.semanticweb.org/dr.kofinyamekye/ontologies/2014/11/untitled-ontology-268>))  org.protege.editor.owl.model.OWLModelManagerImpl[FelixDispatchQueue]
INFO  Rebuilding entity indices...  org.protege.editor.owl.model.OWLModelManagerImpl[FelixDispatchQueue]
INFO  ... rebuilt in 0 ms  org.protege.editor.owl.model.OWLModelManagerImpl[FelixDispatchQueue]
INFO  ... active ontology changed  org.protege.editor.owl.model.OWLModelManagerImpl[FelixDispatchQueue]
INFO  Auto-update last performed: Mon Dec 01 12:00:35 CST 2014  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Auto-update has not been performed today.  Running it.  org.protege.editor.core.ProtegeApplication[FelixDispatchQueue]
INFO  Using OWL API version 3.5.0  org.protege.editor.owl.OWLEditorKit[AWT-EventQueue-0]
INFO  Rebuilding entity indices...  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
INFO  ... rebuilt in 0 ms  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
INFO  Adding root folder: C:\Users\Dr. Kofi Nyamekye\Google Drive\PROTEGE WORKSPACE\ONTOLOGY ...  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
INFO  	...done  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
INFO  loading OntologyID(Anonymous-0) from file:/C:/Users/Dr.%20Kofi%20Nyamekye/Google%20Drive/PROTEGE%20WORKSPACE/ONTOLOGY/flight.owl  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
INFO  Setting active ontology to OntologyID(OntologyIRI(<http://protege.stanford.edu/swbp/flight.owl>))  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
INFO  Rebuilding entity indices...  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
INFO  ... rebuilt in 0 ms  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
INFO  ... active ontology changed  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
INFO  Setting active ontology to OntologyID(OntologyIRI(<http://protege.stanford.edu/swbp/flight.owl>))  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
INFO  Rebuilding entity indices...  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
INFO  ... rebuilt in 0 ms  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
INFO  ... active ontology changed  org.protege.editor.owl.model.OWLModelManagerImpl[AWT-EventQueue-0]
WARN  Error logged  org.protege.editor.core.ui.error.ErrorLog[AWT-EventQueue-0]
java.lang.NullPointerException
	at java.util.TreeMap.compare(Unknown Source)
	at java.util.TreeMap.put(Unknown Source)
	at java.util.TreeSet.add(Unknown Source)
	at org.protege.ontograf.common.ProtegeGraphModel.createDomainRangeRels(ProtegeGraphModel.java:586)
	at org.protege.ontograf.common.ProtegeGraphModel.getDomainRangeRelationships(ProtegeGraphModel.java:599)
	at org.protege.ontograf.common.ProtegeGraphModel.loadDomainRangeRels(ProtegeGraphModel.java:285)
	at org.protege.ontograf.common.ProtegeGraphModel.createIncomingRelationships(ProtegeGraphModel.java:252)
	at org.protege.ontograf.common.ProtegeGraphModel.show(ProtegeGraphModel.java:110)
	at org.protege.ontograf.common.GraphController.showOWLClass(GraphController.java:225)
	at org.protege.ontograf.OntoGrafView.updateView(OntoGrafView.java:219)
	at org.protege.editor.owl.ui.view.cls.AbstractOWLClassViewComponent.updateView(AbstractOWLClassViewComponent.java:36)
	at org.protege.editor.owl.ui.view.cls.AbstractOWLClassViewComponent.updateView(AbstractOWLClassViewComponent.java:19)
	at org.protege.editor.owl.ui.view.AbstractOWLSelectionViewComponent.updateViewContentAndHeader(AbstractOWLSelectionViewComponent.java:202)
	at org.protege.editor.owl.ui.view.AbstractOWLSelectionViewComponent.initialiseOWLView(AbstractOWLSelectionViewComponent.java:119)
	at org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:61)
	at org.protege.editor.core.ui.view.View.createContent(View.java:439)
	at org.protege.editor.core.ui.view.View.createUI(View.java:219)
	at org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:149)
	at java.awt.Component.processHierarchyEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.Component.createHierarchyEvents(Unknown Source)
	at java.awt.Container.createHierarchyEvents(Unknown Source)
	at java.awt.Container.createHierarchyEvents(Unknown Source)
	at java.awt.Container.createHierarchyEvents(Unknown Source)
	at java.awt.Container.createHierarchyEvents(Unknown Source)
	at java.awt.Container.createHierarchyEvents(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at javax.swing.JComponent.setVisible(Unknown Source)
	at javax.swing.JTabbedPane.fireStateChanged(Unknown Source)
	at javax.swing.JTabbedPane$ModelListener.stateChanged(Unknown Source)
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(Unknown Source)
	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(Unknown Source)
	at javax.swing.JTabbedPane.setSelectedIndexImpl(Unknown Source)
	at javax.swing.JTabbedPane.setSelectedIndex(Unknown Source)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$400(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by tudorache** [comment]
Can't reproduce. However, we should add some checks for NPE in the code to prevent this bug.
